/* Exact enumeration of the unrooted binary trees on m leaves (3 <= m <= MAXM) that contain
 * every split in `forced` and no split in `forbidden`, returning the one of least objective
 *
 *     sum over leaf pairs a < b of 2^(-p(a,b)) * dt[a*m + b],
 *
 * where p(a,b) is the number of edges on the path between a and b. Splits are bitmasks over
 * the m leaves, written as the side that does not contain leaf 0.
 *
 * Trees are generated by stepwise addition: leaves 0, 1, 2 meet at one internal node, and
 * leaf k is inserted in turn on each of the 2k - 3 edges of every tree on leaves 0..k-1.
 * Every tree is generated exactly once, (2m - 5)!! in all.
 *
 * Returns the number of trees in the face (0: the face is empty). On return, *best holds the
 * least objective and best_splits[0 .. m-4] the internal splits of a tree attaining it.
 */
#include <string.h>

#define MAXM 16
#define MAXNODES (2 * MAXM - 2)
#define MAXEDGES (2 * MAXM - 3)

static int M;
static int eu[MAXEDGES], ev[MAXEDGES], ne;
static const double *DT;
static const unsigned *FORCED, *FORBIDDEN;
static int NFORCED, NFORBIDDEN;
static long long count;
static double best_obj;
static unsigned best_sp[MAXM];

static int adj[MAXNODES][3], deg[MAXNODES];

static unsigned subtree(int v, int parent, unsigned *splits, int *ns) {
    unsigned mask = v < M ? (1u << v) : 0u;
    for (int k = 0; k < deg[v]; k++) {
        int u = adj[v][k];
        if (u == parent) continue;
        unsigned s = subtree(u, v, splits, ns);
        if (u >= M) splits[(*ns)++] = s;  /* edge v-u is internal: u is an internal node */
        mask |= s;
    }
    return mask;
}

static int depth_from(int src, int *dist) {
    int queue[MAXNODES], head = 0, tail = 0;
    for (int i = 0; i < 2 * M - 2; i++) dist[i] = -1;
    dist[src] = 0;
    queue[tail++] = src;
    while (head < tail) {
        int v = queue[head++];
        for (int k = 0; k < deg[v]; k++) {
            int u = adj[v][k];
            if (dist[u] < 0) { dist[u] = dist[v] + 1; queue[tail++] = u; }
        }
    }
    return 0;
}

static void evaluate(void) {
    int nodes = 2 * M - 2;
    memset(deg, 0, sizeof(int) * nodes);
    for (int e = 0; e < ne; e++) {
        adj[eu[e]][deg[eu[e]]++] = ev[e];
        adj[ev[e]][deg[ev[e]]++] = eu[e];
    }
    /* Root at leaf 0: every subtree mask below it excludes leaf 0, as splits are written. */
    unsigned splits[MAXM];
    int ns = 0;
    subtree(adj[0][0], 0, splits, &ns);
    for (int f = 0; f < NFORCED; f++) {
        int hit = 0;
        for (int s = 0; s < ns; s++) hit |= splits[s] == FORCED[f];
        if (!hit) return;
    }
    for (int f = 0; f < NFORBIDDEN; f++)
        for (int s = 0; s < ns; s++)
            if (splits[s] == FORBIDDEN[f]) return;
    count++;
    double obj = 0.0;
    int dist[MAXNODES];
    for (int a = 0; a < M - 1; a++) {
        depth_from(a, dist);
        for (int b = a + 1; b < M; b++) {
            /* 2^-p as an exact power of two */
            double p = 1.0;
            for (int t = 0; t < dist[b]; t++) p *= 0.5;
            obj += p * DT[a * M + b];
        }
    }
    if (obj < best_obj) {
        best_obj = obj;
        memcpy(best_sp, splits, sizeof(unsigned) * ns);
    }
}

static void insert(int k) {
    if (k == M) { evaluate(); return; }
    int x = M + k - 2;  /* the internal node created when leaf k is inserted */
    int edges = ne;
    for (int e = 0; e < edges; e++) {
        int v = ev[e];
        ev[e] = x;
        eu[ne] = x; ev[ne] = v; ne++;
        eu[ne] = x; ev[ne] = k; ne++;
        insert(k + 1);
        ne -= 2;
        ev[e] = v;
    }
}

long long enumerate_face(int m, const double *dt, const unsigned *forced, int nforced,
                         const unsigned *forbidden, int nforbidden,
                         double *best, unsigned *best_splits) {
    if (m < 3 || m > MAXM) return -1;
    M = m; DT = dt;
    FORCED = forced; NFORCED = nforced;
    FORBIDDEN = forbidden; NFORBIDDEN = nforbidden;
    count = 0;
    best_obj = 1e300;
    ne = 0;
    for (int i = 0; i < 3; i++) { eu[ne] = M; ev[ne] = i; ne++; }
    insert(3);
    *best = best_obj;
    if (count) memcpy(best_splits, best_sp, sizeof(unsigned) * (m - 3));
    return count;
}
